name: Auto Build & Release APK
 
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # 必须开启写入权限以创建 Tag 和 Release
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.8' # 建议与您的项目环境保持一致
          channel: 'stable'
          cache: true

      - name: Install CMake 3.31.4
        run: |
          mkdir -p $ANDROID_HOME/cmake
          curl -L https://github.com/Kitware/CMake/releases/download/v3.31.4/cmake-3.31.4-linux-x86_64.tar.gz -o cmake.tar.gz
          tar -xzf cmake.tar.gz
          mv cmake-3.31.4-linux-x86_64 $ANDROID_HOME/cmake/3.31.4
          echo "$ANDROID_HOME/cmake/3.31.4/bin" >> $GITHUB_PATH
          cmake --version

      - name: Get dependencies
        run: flutter pub get

      - name: Extract version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Detected version: $VERSION"

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-v${{ steps.get_version.outputs.VERSION }}
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          name: Release ${{ steps.get_version.outputs.VERSION }}
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
